trigger:
 - main

pool:
  name: 'MohitPool'

steps:
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r msdocs-python-flask-webapp-quickstart-main/requirements.txt
    python msdocs-python-flask-webapp-quickstart-main/app.py
  displayName: 'Build Python Application'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: 'path/to/artifacts'  # Replace with the path to your build artifacts
#     artifactName: 'python-app-artifact'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts : drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'