trigger:
 - main

pool:
  name: 'MohitPool'

steps:
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r msdocs-python-flask-webapp-quickstart-main/requirements.txt
  displayName: 'Build Python Application'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: 'path/to/artifacts'  # Replace with the path to your build artifacts
#     artifactName: 'python-app-artifact'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts : drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  
    

# - script: |
#     python setup.py sdist
#   displayName: 'Artifact creation'

# - task: CopyFiles@2
#   inputs:
#     targetFolder: $(build.artifactstagingdirectory)

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(build.artifactstagingdirectory)'
#     ArtifactName: 'dist'
#     publishLocation: 'Container'