name: Build and Push to ACR

on:
  workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read

jobs:
  build-and-Push:
    runs-on: ubuntu-latest

    steps:
    # Checkout Repository
    - uses: actions/checkout@v4.2.2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2.1.0
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    # # Docker login to ACR 
    # - name: Docker login to ACR
    #   run: |
    #     az acr login --name ${{ secrets.ACR_NAME }}

    # # Build and Push Image to ACR
    # - name: Build and Push to ACR
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ secrets.ACR_NAME }}.azurecr.io/my-python-app:${{ github.sha }}
