name: Build and Push to ACR

on:
  workflow_dispatch:

jobs:
  build-and-Push:
    runs-on: ubuntu-latest

    steps:
    # Checkout Repository
    - uses: actions/checkout@v4.2.2

    # Login to ACR
    - name: ACR login
      uses: azure/docker-login@v2
      with:
        login_server: ${{ secrets.AZURE_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build and Push Docker Image to ACR
    - name: Build and Push to ACR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: my-python-app:${{ github.sha }}
        file: ./Dockerfile
        context: .
